# Generated by Django 4.1.2 on 2022-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_images_rename_visecategory_visacategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='travel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='travel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
