# Generated by Django 4.1.2 on 2022-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0007_continent_alter_buisnesscategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='description_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='description_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='description_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
