# Generated by Django 4.1.2 on 2022-12-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0009_flag_country_flag_name_en_flag_name_ru_flag_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='visa.countries'),
        ),
    ]
