# Generated by Django 4.1.2 on 2022-12-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0011_remove_flag_country_flag_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='document_1_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_1_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_1_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_2_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_2_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_2_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_3_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_3_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_3_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_4_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_4_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_4_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_5_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_5_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='document_5_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='flag',
            name='country',
        ),
        migrations.AddField(
            model_name='flag',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='visa.countries'),
        ),
    ]
