# Generated by Django 4.1.2 on 2023-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visa", "0013_news_author_news_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dityoslider",
            name="price",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
