# Generated by Django 4.1.2 on 2023-02-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="owner",
        ),
        migrations.AddField(
            model_name="transaction",
            name="fullname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
